# Generated by Django 4.2.7 on 2025-08-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='chat_messag_sender_edb045_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatsession',
            name='chat_sessio_user_id_5fad69_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatsession',
            name='chat_sessio_last_me_f700c1_idx',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='last_message_at',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='document_category',
            field=models.CharField(blank=True, help_text='Category of documents used for RAG response', max_length=100),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='rag_context',
            field=models.JSONField(blank=True, default=dict, help_text='Context retrieved from documents'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='rag_sources',
            field=models.JSONField(blank=True, default=list, help_text='Sources used for RAG response'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender'], name='chat_messag_sender_90e929_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['document_category'], name='chat_messag_documen_bb0b45_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['is_favorite'], name='chat_sessio_is_favo_c8c32d_idx'),
        ),
    ]
