# Generated by Django 4.2.7 on 2025-08-18 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgebase',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='documentchunk',
            options={'ordering': ['chunk_index']},
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='documents_knowled_bcf379_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentchunk',
            name='document_ch_documen_f418b4_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentchunk',
            name='document_ch_embeddi_2bf246_idx',
        ),
        migrations.RemoveIndex(
            model_name='ragquery',
            name='rag_queries_user_id_78f0c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='ragquery',
            name='rag_queries_knowled_de3c8b_idx',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='knowledge_base',
        ),
        migrations.RemoveField(
            model_name='ragquery',
            name='knowledge_base',
        ),
        migrations.RemoveField(
            model_name='ragquery',
            name='retrieved_context',
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(default='general', help_text='Document category for organization', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ragquery',
            name='document_category',
            field=models.CharField(blank=True, help_text='Category of documents used for this query', max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'is_active'], name='documents_user_id_3db954_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['category'], name='documents_categor_f8ad6f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'chunk_index'], name='document_ch_documen_15f3c0_idx'),
        ),
        migrations.AddIndex(
            model_name='ragquery',
            index=models.Index(fields=['user', 'is_active'], name='rag_queries_user_id_f40172_idx'),
        ),
        migrations.AddIndex(
            model_name='ragquery',
            index=models.Index(fields=['document_category'], name='rag_queries_documen_2a6b62_idx'),
        ),
        migrations.DeleteModel(
            name='KnowledgeBase',
        ),
    ]
